spring.application.name=patient-clinical-data-api
spring.datasource.url=jdbc:mysql://localhost:3306/clinicals?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

server.servlet.context-path=/patient-services
# Application-wide logging level
logging.level.root=INFO

# Your application package
logging.level.com.vimal.clinicalsapi.patientsdata=DEBUG

# Hibernate SQL
logging.level.org.hibernate.SQL=DEBUG

# Hibernate bind parameter values
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Log file
logging.file.name=logs/patient-clinical-data-api.log


# File log format
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

# Keep the file from growing indefinitely
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=7
logging.logback.rollingpolicy.total-size-cap=100MB